### ISSUE TITLE
md5 not available on CentOs

### ISSUE THREAD

**Issue by hpagey** [Workday/vizzy#41]
The upload script runs md5 command which is not available on centos. Centos has md5sum. It might be good idea to calculate the hash in platform independent way.

**Comment by socbazghi** [comment]
on `upload_images_to_server.rb` line 255 you can replace
`md5 = md5 -q #{file}`
with
`md5 = Digest::MD5.file(file).hexdigest`

worked for me on linux as it uses the md5 digest gem instead of the os-aware shell command

**Comment by kennyko** [comment]
Resolved in #49
